name = "pog-cli-signal"
main = "index.ts"
compatibility_date = "2024-11-12"

[[kv_namespaces]]
binding = "CACHE"
id = "3015b76d2d1b408a99066d1e793d8435"
preview_id = "3015b76d2d1b408a99066d1e793d8435"

[observability]
enabled = true
