name = "pog-bridge"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[dev]
port = 8788

[[durable_objects.bindings]]
name = "OBSERVABILITY_LIMITER"
class_name = "ObservabilityLimiter"

[[migrations]]
tag = "v1"
new_classes = ["ObservabilityLimiter"]
